/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Button: typeof import('./components/common/buttons/Button/Button.vue')['default']
    ButtonBack: typeof import('./components/common/buttons/ButtonBack.vue')['default']
    CardPanel: typeof import('./components/common/panels/CardPanel.vue')['default']
    FormActionPanel: typeof import('./components/common/panels/FormActionPanel/FormActionPanel.vue')['default']
    FormPanel: typeof import('./components/common/panels/FormPanel/FormPanel.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchField: typeof import('./components/common/inputs/SearchField.vue')['default']
    SelectField: typeof import('./components/common/inputs/SelectField/SelectField.vue')['default']
    Textfield: typeof import('./components/common/inputs/Textfield/Textfield.vue')['default']
  }
}
