const TextFieldDefaults = {
  active: false,
  appendIcon: undefined,
  appendInnerIcon: undefined,
  autofocus: false,
  baseColor: undefined,
  bgColor: undefined,
  centerAffix: undefined,
  clearable: false,
  clearIcon: '$clear',
  // color: undefined - omitted
  counter: false,
  counterValue: undefined,
  density: undefined,
  direction: undefined,
  dirty: false,
  disabled: false,
  error: undefined,
  // errorMessages: [] - omitted
  flat: false,
  focused: false,
  hideSpinButtons: false,
  hint: undefined,
  id: undefined,
  // label: undefined - omitted
  loading: false,
  maxErrors: 1,
  maxWidth: undefined,
  messages: undefined,
  minWidth: undefined,
  // modelValue: undefined,
  name: undefined,
  persistentClear: false,
  persistentCounter: false,
  persistentHint: false,
  persistentPlaceholder: false,
  placeholder: undefined,
  prefix: undefined,
  prependIcon: undefined,
  prependInnerIcon: undefined,
  readonly: false,
  reverse: false,
  role: undefined,
  // rounded: undefined - omitted
  // rules: undefined, - omitted
  singleLine: undefined,
  suffix: undefined,
  theme: undefined,
  tile: undefined,
  type: 'text',
  validateOn: undefined,
  validationValue: undefined,
  width: undefined,
}

export default TextFieldDefaults
